### ISSUE TITLE
Failed running an example file.

### ISSUE THREAD

**Issue by Shreya-droid** [raghavagps/mutation_bench#1]
I was trying to run an example file. I assume I've installed/loaded all the requirements. Please help with what might be the issue. Also, find the attached screenshot of my terminal where the script failed. 

![terminal_shreya](https://user-images.githubusercontent.com/61824825/174720410-b8dcdcc5-baa9-471a-85d6-0b9b47d40aed.png)

**Comment by sumeetpatiyal** [comment]
Dear Shreya,

This seems to be error of database file. So, kindly download the file using the link https://github.com/sumeetpatiyal/muthrp/raw/main/humandb.zip and rerun the script. It is working perfectly fine at our end. Please drop us a message if the problem still persist.

Thank You

**Comment by Shreya-droid** [comment]
This time still the error persists but on a different line in a script.
Please do check. Also, find attached a screenshot- It says 100% run
assuming it ran but then why the error and didn't produce result files.
I am simply running the example files as mentioned with all the
fulfilled requirements. If still, you think something is missing please let
me know.

Thanks
Shreya Sharma

[image: image.png]

**Comment by sumeetpatiyal** [comment]
Dear Shreya,

There must be some issue with the libraries as I have ran the code and its running completely fine. My suggestion is that you can again clone the directory and try to run the code. If the problem will persist, let me know.

Thank You
